export var listmodelvehichle = [
    {jenis:'Car', brand:'toyota',value:'agya',name:'Agya'},
    {jenis:'Car',brand:'toyota',value:'avanza',name:'Avanza'},
    {jenis:'Car',brand:'toyota',value:'alphard',name:'Alphard'},
    {jenis:'Car',brand:'toyota',value:'calya',name:'Calya'},
    {jenis:'Car',brand:'toyota',value:'camry',name:'Camry'},
    {jenis:'Car',brand:'toyota',value:'etios',name:'Etios'},
    {jenis:'Car',brand:'toyota',value:'fortuner',name:'Fortuner'},
    {jenis:'Car',brand:'toyota',value:'kijanginnova',name:'Kijang Innova'},
    {jenis:'Car',brand:'toyota',value:'rush',name:'Rush'},
    {jenis:'Car',brand:'toyota',value:'sienta',name:'Sienta'},
    {jenis:'Car',brand:'toyota',value:'veloz',name:'Veloz'},
    {jenis:'Car',brand:'toyota',value:'vellfire',name:'Vellfire'},
    {jenis:'Car',brand:'toyota',value:'vios',name:'Vios'},
    {jenis:'Car',brand:'toyota',value:'yaris',name:'Yaris'},

    {jenis:'Car',brand:'daihatsu',value:'ayla',name:'Ayla'},
    {jenis:'Car',brand:'daihatsu',value:'copen',name:'Copen'},
    {jenis:'Car',brand:'daihatsu',value:'granmax',name:'Gran Max'},
    {jenis:'Car',brand:'daihatsu',value:'luxio',name:'Luxio'},
    {jenis:'Car',brand:'daihatsu',value:'sigra',name:'Sigra'},
    {jenis:'Car',brand:'daihatsu',value:'sirion',name:'Sirion'},
    {jenis:'Car',brand:'daihatsu',value:'terios',name:'Terios'},
    {jenis:'Car',brand:'daihatsu',value:'xenia',name:'Xenia'},

    {jenis:'Car',brand:'honda',value:'brio',name:'Brio'},
    {jenis:'Car',brand:'honda',value:'brv',name:'BR-V'},
    {jenis:'Car',brand:'honda',value:'crv',name:'CR-V'},
    {jenis:'Car',brand:'honda',value:'city',name:'City'},
    {jenis:'Car',brand:'honda',value:'jazz',name:'Jazz'},
    {jenis:'Car',brand:'honda',value:'mobillio',name:'Mobillio'},

    {jenis:'Car',brand:'mitsubishi',value:'xpander',name:'Xpander'},
    {jenis:'Car',brand:'mitsubishi',value:'outlandersport',name:'Outlander Sport'},
    {jenis:'Car',brand:'mitsubishi',value:'pajerosport',name:'Pajero Sport'},

    {jenis:'Car',brand:'nissan',value:'grandlivina',name:'Grand Livina'},
    {jenis:'Car',brand:'nissan',value:'juke',name:'Juke'},
    {jenis:'Car',brand:'nissan',value:'march',name:'March'},
    {jenis:'Car',brand:'nissan',value:'serena',name:'Serena'},
    {jenis:'Car',brand:'nissan',value:'xtrail',name:'X-Trail'},

    {jenis:'Car',brand:'suzuki',value:'apv',name:'APV'},
    {jenis:'Car',brand:'suzuki',value:'ertiga',name:'Ertiga'},
    {jenis:'Car',brand:'suzuki',value:'grandvitara',name:'Grand Vitara'},
    {jenis:'Car',brand:'suzuki',value:'karimun',name:'Karimun'},
    {jenis:'Car',brand:'suzuki',value:'scross',name:'S-Cross'},
    {jenis:'Car',brand:'suzuki',value:'splash',name:'Splash'},
    {jenis:'Car',brand:'suzuki',value:'swift',name:'Swift'},

    {jenis:'Car',brand:'mazda',value:'cx2',name:'CX-2'},
    {jenis:'Car',brand:'mazda',value:'cx3',name:'CX-3'},
    {jenis:'Car',brand:'mazda',value:'cx5',name:'CX-5'},
    {jenis:'Car',brand:'mazda',value:'mazda2',name:'Mazda 2'},
    {jenis:'Car',brand:'mazda',value:'mazda3',name:'Mazda 3'},
    {jenis:'Car',brand:'mazda',value:'mazda5',name:'Mazda 5'},

    {jenis:'Car',brand:'wuling',value:'almaz',name:'Almaz'},
    {jenis:'Car',brand:'wuling',value:'cortez',name:'Cortez'},
    {jenis:'Car',brand:'wuling',value:'confero',name:'Confero'},

    {jenis:'Motorcyle',brand:'honda',value:'adv',name:'ADV'},
    {jenis:'Motorcyle',brand:'honda',value:'beat',name:'Beat'},
    {jenis:'Motorcyle',brand:'honda',value:'genio',name:'Genio'},
    {jenis:'Motorcyle',brand:'honda',value:'megapro',name:'Mega Pro'},
    {jenis:'Motorcyle',brand:'honda',value:'revo',name:'Revo'},
    {jenis:'Motorcyle',brand:'honda',value:'vario',name:'Vario'},
    {jenis:'Motorcyle',brand:'honda',value:'supragtr',name:'Supra-GTR'},
    {jenis:'Motorcyle',brand:'honda',value:'suprax',name:'Supra-X'},
    {jenis:'Motorcyle',brand:'honda',value:'sonic',name:'Sonic'},
    {jenis:'Motorcyle',brand:'honda',value:'pcx',name:'PCX'},
    {jenis:'Motorcyle',brand:'honda',value:'verza',name:'Verza'},

    {jenis:'Motorcyle',brand:'suzuki',value:'gsx',name:'GSX'},
    {jenis:'Motorcyle',brand:'suzuki',value:'satriaf',name:'Satria-F'},
    {jenis:'Motorcyle',brand:'suzuki',value:'smash',name:'Smash'},
    {jenis:'Motorcyle',brand:'suzuki',value:'address',name:'Address'},

    {jenis:'Motorcyle',brand:'yamaha',value:'aerox',name:'Aerox'},
    {jenis:'Motorcyle',brand:'yamaha',value:'fino',name:'Fino'},
    {jenis:'Motorcyle',brand:'yamaha',value:'lexi',name:'Lexi'},
    {jenis:'Motorcyle',brand:'yamaha',value:'mio',name:'Mio'},
    {jenis:'Motorcyle',brand:'yamaha',value:'nmax',name:'Nmax'},
    {jenis:'Motorcyle',brand:'yamaha',value:'soul',name:'Soul'},
    {jenis:'Motorcyle',brand:'yamaha',value:'xride',name:'X-Ride'},
]

export var vehicle = [
    {jenis:'Car',value:'toyota',brand:'TOYOTA'},
    {jenis:'Car',value:'daihatsu',brand:'DAIHATSU'},
    {jenis:'Car',value:'honda',brand:'HONDA'},
    {jenis:'Car',value:'mitsubishi',brand:'MITSUBISHI'},
    {jenis:'Car',value:'nissan',brand:'NISSAN'},
    {jenis:'Car',value:'suzuki',brand:'SUZUKI'},
    {jenis:'Car',value:'mazda',brand:'MAZDA'},
    {jenis:'Car',value:'wuling',brand:'WULING'},
    {jenis:'Motorcyle',value:'honda',brand:'HONDA'},
    {jenis:'Motorcyle',value:'suzuki',brand:'SUZUKI'},
    {jenis:'Motorcyle',value:'yamaha',brand:'YAMAHA'},
    // {jenis:'Motorcyle',value:'kawasaki',brand:'KAWASAKI'}
]